# Generated by Django 4.2.19 on 2025-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, unique=True)),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_folder_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_resumes', models.JSONField(blank=True, null=True)),
                ('unmatched_resumes', models.JSONField(blank=True, null=True)),
                ('analytics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, unique=True)),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_folder_id', models.CharField(max_length=255)),
            ],
        ),
    ]
